# Generated by Django 4.2.7 on 2024-01-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_available',
        ),
    ]
